server:
  port: 8888
  servlet:
    context-path: /SpringBoot2Tech
spring:
  profiles:
    include: datasource, swagger
  datasource:
    druid:
      filter:
        logback:
          statement-executable-sql-log-enable: true
